name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./gradlew --no-daemon --max-workers 8 --build-cache assembleRelease

  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validating Ktlint
        run: ./gradlew --no-daemon --max-workers 8 --build-cache ktlintCheck

  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Verifying detekt
        run: ./gradlew --no-daemon --max-workers 8 --build-cache detekt

  test:
    name: Instrumentation tests
    runs-on: macos-11
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew cAT